theme = "catppuccin_mocha"

[editor]
line-number="relative"
mouse = false
auto-completion = true
idle-timeout = 50
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control","spacer","spacer", "diagnostics"]
center = ["file-name"]
right = ["position", "file-encoding", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
auto-signature-help = true
display-signature-help-docs = true
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
