gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showRandomTip: false
git:
  autoFetch: true
  mainBranches:
    - main
    - master
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
os:
  edit: 'hx {{filename}}'
  editAtLine: 'hx {{filename}}:{{line}}'
