gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showRandomTip: false

git:
  autoFetch: true
  mainBranches:
    - main
    - master

os:
  edit: 'nvim --cmd "let g:lazygit=1" {{filename}}'
  editAtLine: 'nvim --cmd "let g:lazygit=1" +{{line}} {{filename}}'
