[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.primary]
background = "#0a0c10"
foreground = "#f0f3f6"

[colors.cursor]
text = "#0a0c10"
cursor = "#f0f3f6"

[colors.normal]
black = "#7a828e"
red = "#ff9492"
green = "#26cd4d"
yellow = "#f0b72f"
blue = "#71b7ff"
magenta = "#cb9eff"
cyan = "#addcff"
white = "#d9dee3"

[colors.bright]
black = "#9ea7b3"
red = "#ffb1af"
green = "#4ae168"
yellow = "#f7c843"
blue = "#91cbff"
magenta = "#dbb7ff"
cyan = "#caeaff"
white = "#f0f3f6"
